### ISSUE TITLE
"npm test" fails on Windows

### ISSUE THREAD

**Issue by sailorsteve** [ThirstyHead/es6tests#1]
Running `npm test` on Windows 7 results in the following error message from eslint: _SyntaxError: Unexpected token case_
Changing package.json from
`"scripts": {
    "pretest": "node node_modules/.bin/eslint spec",
    "test": "node index"
  },
`
to
`"scripts": {
    "pretest": "node_modules/.bin/eslint spec",
    "test": "node index"
  },
`
fixes the problem.
I am running node v4.2.4 and npm v3.5.2.

**Comment by zulrang** [comment]
Thanks for this!  Worked for me.

**Comment by scottdavis99** [comment]
Hey @sailorsteve, 

Good catch! Sorry for the lag in buttoning up this issue (I've been heads-down with http://meaningfuljs.com), but it is now fixed in v0.1.1.

Thx.
